### ISSUE TITLE
non-hexadecimal number found in fromhex() arg at position 0

### ISSUE THREAD

**Issue by ighostx** [alexbers/mtprotoproxy#122]
Help guys :) Port and sercet in config changed.

Traceback (most recent call last):
  File "mtprotoproxy.py", line 1072, in handle_client_wrapper
    await handle_client(reader, writer)
  File "mtprotoproxy.py", line 970, in handle_client
    timeout=CLIENT_HANDSHAKE_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "mtprotoproxy.py", line 661, in handle_handshake
    secret = bytes.fromhex(USERS[user])
ValueError: non-hexadecimal number found in fromhex() arg at position 0

Task exception was never retrieved
future: <Task finished coro=<handle_client_wrapper() done, defined at mtprotoproxy.py:1070> exception=ValueError('non-hexadecimal number found in fromhex() arg at position 0')>
Traceback (most recent call last):
  File "mtprotoproxy.py", line 1072, in handle_client_wrapper
    await handle_client(reader, writer)
  File "mtprotoproxy.py", line 970, in handle_client
    timeout=CLIENT_HANDSHAKE_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "mtprotoproxy.py", line 661, in handle_handshake
    secret = bytes.fromhex(USERS[user])
ValueError: non-hexadecimal number found in fromhex() arg at position 0

Task exception was never retrieved
future: <Task finished coro=<handle_client_wrapper() done, defined at mtprotoproxy.py:1070> exception=ValueError('non-hexadecimal number found in fromhex() arg at position 0')>
Traceback (most recent call last):
  File "mtprotoproxy.py", line 1072, in handle_client_wrapper
    await handle_client(reader, writer)
  File "mtprotoproxy.py", line 970, in handle_client
    timeout=CLIENT_HANDSHAKE_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "mtprotoproxy.py", line 661, in handle_handshake
    secret = bytes.fromhex(USERS[user])
ValueError: non-hexadecimal number found in fromhex() arg at position 0

Task exception was never retrieved
future: <Task finished coro=<handle_client_wrapper() done, defined at mtprotoproxy.py:1070> exception=ValueError('non-hexadecimal number found in fromhex() arg at position 0')>
Traceback (most recent call last):
  File "mtprotoproxy.py", line 1072, in handle_client_wrapper
    await handle_client(reader, writer)
  File "mtprotoproxy.py", line 970, in handle_client
    timeout=CLIENT_HANDSHAKE_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "mtprotoproxy.py", line 661, in handle_handshake
    secret = bytes.fromhex(USERS[user])
ValueError: non-hexadecimal number found in fromhex() arg at position 0

**Comment by alexbers** [comment]
It seems there is a non-hexadecimal number in your secret at position 0. Please use only hexadecimal numbers (0123456789abcdef)
