### ISSUE TITLE
non-first user can't connect to server

### ISSUE THREAD

**Issue by n06rin** [alexbers/mtprotoproxy#144]
Hi! I'm set in config.py several users
```
# name -> secret (32 hex chars)
USERS = {
    "userFoo":  "xxx...xx",
    "userBar": "xxx...xx",
    "userBaz": "xx...xx",
}
```
end when server started I see at output:
```
userBaz: tg://proxy?server=<serverIp>&port=<serverPort>&secret="xxx...xx"
userBaz: tg://proxy?server=<serverIp>&port=<serverPort>&secret=xxx...xx (new)
userBar: tg://proxy?server=<serverIp>&port=<serverPort>&secret="xxx...xx"
userBar: tg://proxy?server=<serverIp>&port=<serverPort>&secret="xxx...xx" (new)
userFoo: tg://proxy?server=<serverIp>&port=<serverPort>&secret="xxx...xx"
userFoo: tg://proxy?server=<serverIp>&port=<serverPort>&secret="xxx...xx" (new)
```

But, when user connected by link created not for first user (userBar, userBaz), he can't connect, and server is throwing error at console:
```
ValueError: non-hexadecimal number found in fromhex() arg at position 29
 Traceback (most recent call last):
   File "mtprotoproxy.py", line 1560, in handle_client_wrapper
     await handle_client(reader, writer)
   File "mtprotoproxy.py", line 1436, in handle_client
     timeout=config.CLIENT_HANDSHAKE_TIMEOUT)
   File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
     return fut.result()
   File "mtprotoproxy.py", line 1151, in handle_handshake
     secret = bytes.fromhex(config.USERS[user])
```

**Comment by alexbers** [comment]
Hello, please, make sure that you are using only hexdecimal numbers in the secret. Hexdecimal numbers are "01234567890abcdef"

The error non-hexadecimal number found in fromhex() arg at position 29 happens when there some not hexdecimal number in the secret (at position 29).

**Comment by n06rin** [comment]
oh, thank you!
