### ISSUE TITLE
some unknow issue!

### ISSUE THREAD

**Issue by kooran** [alexbers/mtprotoproxy#190]
Hello , i did as instruction said, after "docker-compose up -d"  i get the "success " and green "done" messages! but i can't connect, i run docker-compose logs and i get this long logs! :

Attaching to mtprotoproxy_mtprotoproxy_1
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2277, in <module>
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 103, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 201, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 860, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 23
mtprotoproxy_1  |     TLS_DOMAIN = "mail.google.com"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent

**Comment by alexbers** [comment]
Hello,

It seems you have an indentation errors in the config.py. Please make sure that all line are indented properly (e.g. no extra spaces or tabs in the beginning)

**Comment by prhobb** [comment]
Delete spaces before TLS_DOMAIN in the config.py
