### ISSUE TITLE
crash in mtprotoproxy

### ISSUE THREAD

**Issue by golil** [alexbers/mtprotoproxy#196]
hi

i use mtprotoproxy in port 80 but after few day mtprotoproxy crashed i see this output in systemctl status:
```
Feb 22 14:39:56 oreoserver python3[1012]: Traceback (most recent call last):
Feb 22 14:39:56 oreoserver python3[1012]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 168, in _accept_connection
Feb 22 14:39:56 oreoserver python3[1012]:     conn, addr = sock.accept()
Feb 22 14:39:56 oreoserver python3[1012]:   File "/usr/lib/python3.6/socket.py", line 205, in accept
Feb 22 14:39:56 oreoserver python3[1012]:     fd, addr = self._accept()
Feb 22 14:39:56 oreoserver python3[1012]: OSError: [Errno 24] Too many open files
Feb 22 14:39:56 oreoserver python3[1012]: socket.accept() out of system resource
Feb 22 14:39:56 oreoserver python3[1012]: socket: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 80)>
Feb 22 14:39:56 oreoserver python3[1012]: Traceback (most recent call last):
Feb 22 14:39:56 oreoserver python3[1012]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 168, in _accept_connection
Feb 22 14:39:56 oreoserver python3[1012]:     conn, addr = sock.accept()
Feb 22 14:39:56 oreoserver python3[1012]:   File "/usr/lib/python3.6/socket.py", line 205, in accept
Feb 22 14:39:56 oreoserver python3[1012]:     fd, addr = self._accept()
Feb 22 14:39:56 oreoserver python3[1012]: OSError: [Errno 24] Too many open files
Feb 22 14:39:56 oreoserver python3[1012]: socket.accept() out of system resource
Feb 22 14:39:56 oreoserver python3[1012]: socket: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 80)>
```
the crash status and logs goes on until the whole VPS storage is filled with this logs. If I restart the service returns to normal state, but after a few days begins again.
This can happen because i use port 80 ?

**Comment by alexbers** [comment]
Hello,

It seems you hit open files limit. As I can see you are using systemd for running the proxy. Please, make sure you have LimitNOFILE=infinity in the unit file.

The more detailed information is here: https://github.com/alexbers/mtprotoproxy/wiki/Running-Without-Docker

**Comment by golil** [comment]
thanks
create new systemd service file with limit no file config
