### ISSUE TITLE
Can I use pypy to run this program?

### ISSUE THREAD

**Issue by CCCAUCHY** [alexbers/mtprotoproxy#264]

**Comment by alexbers** [comment]
Yes, you can

**Comment by CCCAUCHY** [comment]
> Yes, you can

I use "apt install pypy" to install pypy, and then use "pypy mtprotoproxy.py" to run, and then it reports many errors

**Comment by CCCAUCHY** [comment]
> Yes, you can

```
 pypy mtprotoproxy.py
  File "mtprotoproxy.py", line 359
    print(msg, flush=True, file=sys.stderr)
                    ^
SyntaxError: invalid syntax (expected ')')
```

**Comment by alexbers** [comment]
it should be pypy version 3 instead 2

**Comment by CCCAUCHY** [comment]
> it should be pypy version 3 instead 2

`pypy3 mtprotoproxy.py`

```
Traceback (most recent call last):
  File "mtprotoproxy.py", line 483, in <module>
    myrandom = MyRandom()
  File "mtprotoproxy.py", line 464, in __init__
    self.encryptor = create_aes_ctr(key, iv)
  File "mtprotoproxy.py", line 333, in create_aes_ctr
    cipher = Cipher(algorithms.AES(key), modes.CTR(iv_bytes), default_backend())
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 114, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
```
