### ISSUE TITLE
how I can adversative my channel to proxy users?

### ISSUE THREAD

**Issue by sae13** [alexbers/mtprotoproxy#3]
Hi there I saw some mtproxies can show a channel as ads how i can add that?

**Comment by alexbers** [comment]
Hi, I seen only one channel which does it, and they tell they use proxy from Telegram authors. I spent last day reading the source code of telegram desktop client to see how it gets ad settings. The client does help.getProxyData api call and got the promoted channel info from telegram server. The most interesting thing is that this call doesn't have any parameters, so the telegram somehow knows about a proxy. 

For now it is unknown for general public how the proxy should tell the telegram server about himself. Probably the proxy should inject an api call with his identifier in the beginning of proxied tcp-connection. And there such be some way to connect the proxy identifier with ad channel. It is also unknown yet.

One more interesting thing I found is that telegram client updates ad channel info every hour, so probably there should be some method to tell telegram the new channel to advertise.

I am continuously monitoring the internet about information about the topic. When more details will be known, I'll implement the ads.

**Comment by p1ratrulezzz** [comment]
https://github.com/TelegramMessenger/MTProxy this one has this ability (sends proxy tag)

**Comment by p1ratrulezzz** [comment]
@sae13, you can but you won't see advertised channel in it because this proxy is missing proxy tag configuration. Just wait until it will be added

**Comment by kingjan123** [comment]
@alexbers https://github.com/TelegramMessenger/MTProxy
Check it again plz

**Comment by alexbers** [comment]
I am working on this functionality. The Telegram developers added one more layer of proxies to support advertising - so called middle-proxies. They are between proxy and telegram servers. 

To implement advertising one need to communicate with those proxies using MTProto calls. Now I read the MTProxy source, found the protocol details and implementing them.

**Comment by p1ratrulezzz** [comment]
Finally will be readable code for this:)

**Comment by seega** [comment]
@alexbers as I understood, transfer of the tag works only through Ipv4 now?

**Comment by alexbers** [comment]
The first version of tagging was implemented: https://github.com/alexbers/mtprotoproxy/commit/fee5a0c05ae855d97e12a46253e4ad50395df17c. 

The patch is quite big because the Telegram uses tricky scheme to pass tags including an additional level of middware proxies.

The support for ipv6 will be added in a short time.

**Comment by alexbers** [comment]
The issue with ipv6 should be fixed by https://github.com/alexbers/mtprotoproxy/commit/0648b41c17b0a05c53e20306113603fb0af9e546. Further ipv6 support is coming soon.

**Comment by p1ratrulezzz** [comment]
Since latest git pull (which was fee5a0c) the memory consumption is ~600mb and goes fine.

**Comment by seriyps** [comment]
@p1ratrulezzz 600mb for how many connections?

**Comment by p1ratrulezzz** [comment]
Update:
Ram: ~400MB
Connections count: 11529

**Comment by alexbers** [comment]
Are that connection simultaneous?

**Comment by p1ratrulezzz** [comment]
No, just connections for last minute I guess. I artificially limited Max rate to 50 requests per ip (using iptables) and Max 60000 connections at the same time . According to the stats there are about 400 users connected to the proxy. Works well for 2 days already, advertising works too

**Comment by alexbers** [comment]
Nice! Please let me know if there will be some issues with memory and other stuff.

**Comment by p1ratrulezzz** [comment]
```
Fatal read error on socket transport                                                                                                                                                                                
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbccf1d1470>                                                                                                                                           
transport: <_SelectorSocketTransport fd=21780 read=polling write=<polling, bufsize=66392>>                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready                                                                                                                                    
    data = self._sock.recv(self.max_size)                                                                                                                                                                           
TimeoutError: [Errno 110] Connection timed out                                                                                                                                                                      
Fatal read error on socket transport                                                                                                                                                                                
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbcafb093c8>                                                                                                                                           
transport: <_SelectorSocketTransport fd=9501 read=polling write=<polling, bufsize=33045>>                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready                                                                                                                                    
    data = self._sock.recv(self.max_size)                                                                                                                                                                           
TimeoutError: [Errno 110] Connection timed out                                                                                                                                                                      
Fatal read error on socket transport                                                                                                                                                                                
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbcb139eda0>                                                                                                                                           
transport: <_SelectorSocketTransport fd=10111 read=polling write=<idle, bufsize=0>>                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready                                                                                                                                    
    data = self._sock.recv(self.max_size)                                                                                                                                                                           
TimeoutError: [Errno 110] Connection timed out                                                                                                                                                                      
Fatal read error on socket transport                                                                                                                                                                                
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbcbd377390>                                                                                                                                           
transport: <_SelectorSocketTransport fd=25297 read=polling write=<idle, bufsize=0>>                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready                                                                                                                                    
    data = self._sock.recv(self.max_size)                                                                                                                                                                           
TimeoutError: [Errno 110] Connection timed out                                                                                                                                                                      
Fatal read error on socket transport                                                                                                                                                                                
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbcb08d9278>                                                                                                                                           
transport: <_SelectorSocketTransport fd=27915 read=polling write=<idle, bufsize=0>>                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready                                                                                                                                    
    data = self._sock.recv(self.max_size)                                                                                                                                                                           
TimeoutError: [Errno 110] Connection timed out                                                                                                                                                                      
Fatal write error on socket transport                                                                                                                                                                               
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fbcb2c2c2e8>
transport: <_SelectorSocketTransport fd=23259 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _write_ready
    n = self._sock.send(self._buffer)
TimeoutError: [Errno 110] Connection timed out
```

Started proxy 12h ago.

It works but I have these errors in log. Memory consuption ~1.60GB, CPU ~60. I have about 1000 users according to stats

**Comment by alexbers** [comment]
These errors occurs when proxy tries to send the data to the client but can't. This is likely because the client was lost (for example it is a mobile client and his phone was turned off).

I plan to handle those errors in a less noisy way. Also, I plan to add the debug information in the important cases, for example when connection to telegram side fails.

**Comment by alexbers** [comment]
The timeout errors shouldn't appear after https://github.com/alexbers/mtprotoproxy/commit/07780602d1cd71b628519a7f746a2c55165fe9bd

**Comment by seriyps** [comment]
> The timeout errors should disappear after 0778060

I would suggest to use python's logging framework for this

**Comment by alexbers** [comment]
What are advantages of using that framework over these two tiny functions?
```
def print_stderr(*params):
    print(*params, file=sys.stderr, flush=True)
def print_stdout(*params):
    print(*params, file=sys.stdout, flush=True)
```
