### ISSUE TITLE
crash after one minute 

### ISSUE THREAD

**Issue by Neo-vortex** [alexbers/mtprotoproxy#57]
the proxy was working without any problem til this morning.
after i run the proxy is works for one minute or so then crashes with this error:

`Task exception was never retrieved
future: <Task finished coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py:496> exception=OSError(22, 'The specified network name is no longer available', None, 64, None)>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 499, in accept_coro
    await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 732, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 488, in finish_accept
    ov.getresult()
OSError: [WinError 64] The specified network name is no longer available
Accept failed on a socket
socket: <socket.socket fd=612, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 6969)>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\proactor_events.py", line 637, in loop
    conn, addr = f.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 499, in accept_coro
    await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 732, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\windows_events.py", line 488, in finish_accept
    ov.getresult()
OSError: [WinError 64] The specified network name is no longer available
`

**Comment by alexbers** [comment]
It likely your network interface is flapping (often goes up/down) and Python handles this situation incorrectly - it shuts down the listening socket.

I'll try to figure out how it can be fixed in Python, but it can take time, so you can fix network interfaces issues, if any.
