### ISSUE TITLE
Help me docker compose

### ISSUE THREAD

**Issue by MrMstafa** [alexbers/mtprotoproxy#60]
root@DeaD:~/mtprotoproxy# docker-compose up --build -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 14, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 9, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/dist-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 18, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by alexbers** [comment]
Hello, you can try to install pyopenssl using package manager of your OS or with pip (pip install pyopenssl). Also, you can use proxy without docker, just with python3.6 mtprotoproxy.py

**Comment by MrMstafa** [comment]
@alexbers
Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fb966987c88>
transport: <_SelectorSocketTransport fd=27 read=polling write=<idle, bufsize=0»
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused
Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fb9668c4e80>
transport: <_SelectorSocketTransport fd=86 read=polling write=<idle, bufsize=0»
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused
--------------------------------------------------------------------------------
This error occurs after the project is executed, and some users can not connect to the proxy
@alexbers
