### ISSUE TITLE
OSError: [Errno 92] Protocol not available

### ISSUE THREAD

**Issue by pasha-zzz** [alexbers/mtprotoproxy#75]
Router (arm) + entware, python 3.7.1.

Task exception was never retrieved
future: <Task finished coro=<handle_client_wrapper() done, defined at /opt/mtproxy/mtprotoproxy.py:995> exception=OSError(92, 'Protocol not available')>
Traceback (most recent call last):
  File "/opt/mtproxy/mtprotoproxy.py", line 997, in handle_client_wrapper
    await handle_client(reader, writer)
  File "/opt/mtproxy/mtprotoproxy.py", line 904, in handle_client
    set_ack_timeout(writer_clt.get_extra_info("socket"), CLIENT_ACK_TIMEOUT)
  File "/opt/mtproxy/mtprotoproxy.py", line 654, in set_ack_timeout
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_USER_TIMEOUT, timeout*1000)
OSError: [Errno 92] Protocol not available

**Comment by alexbers** [comment]
I've commited ignoring those kind of errors: https://github.com/alexbers/mtprotoproxy/commit/b0cb48f684a9b6a710f7b6ec7668c56b5dbcfbca. It seems you kernel doesn't support this option.

By the way, which kernel version are you use?

**Comment by pasha-zzz** [comment]
2.6.36.4brcmarm

**Comment by alexbers** [comment]
The TCP_USER_TIMEOUT option has appeared since Linux 2.6.37 :)

Anyway, it should work now.

**Comment by pasha-zzz** [comment]
All fine, now there is:
Unable to connect to 149.154.167.51 443

Overlaps with following blocked subnets:
149.154.160.0/20 - Telegram Messenger Network
149.154.164.0/22 - Telegram Messenger Network
149.154.167.51/32 - Telegram Messenger Network

I think to connect via Tor. Upstream socks proxy isnt supported? Only socksify?

**Comment by alexbers** [comment]
Upstream socks proxy is not implemented yet, I didn't test with socksify. 

I would advise vpn (openvpn or others) or ipv6, they should work. The tor also should work, but it will be slow.

If you don't have Ipv6, you can use teredo-tunnels, is should be by default on windows and available as miredo (https://en.wikipedia.org/wiki/Miredo) in Linux and BSD distributions.
