### ISSUE TITLE
Task exception was never retrieved [Error]

### ISSUE THREAD

**Issue by hookzof** [alexbers/mtprotoproxy#77]
Sometimes in the console you can see:

```
Task exception was never retrieved
future: <Task finished coro=<handle_client.<locals>.connect_reader_to_writer() done, defined at mtprotoproxy.py:940> exception=AttributeError("'NoneType' object has no attribute 'shutdown'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "mtprotoproxy.py", line 950, in connect_reader_to_writer
    wr.write_eof()
  File "mtprotoproxy.py", line 272, in write_eof
    return self.upstream.write_eof()
  File "mtprotoproxy.py", line 272, in write_eof
    return self.upstream.write_eof()
  File "/usr/lib/python3.5/asyncio/streams.py", line 300, in write_eof
    return self._transport.write_eof()
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 807, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
AttributeError: 'NoneType' object has no attribute 'shutdown'
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
Debian 9

**Comment by alexbers** [comment]
It is likely due this bug in Python: https://github.com/python/cpython/pull/7149. Could you please retry with Python 3.6?
